// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ISTA_LM
void ISTA_LM(int p, int H, int K, const arma::ivec& Ks, const arma::ivec& pk, const arma::mat& XtX, const arma::vec& Xty, const arma::vec& lambda, double L, int max_it, double eps, arma::vec& x0, arma::vec& xk, int penalty, int& iter);
RcppExport SEXP _scoop_ISTA_LM(SEXP pSEXP, SEXP HSEXP, SEXP KSEXP, SEXP KsSEXP, SEXP pkSEXP, SEXP XtXSEXP, SEXP XtySEXP, SEXP lambdaSEXP, SEXP LSEXP, SEXP max_itSEXP, SEXP epsSEXP, SEXP x0SEXP, SEXP xkSEXP, SEXP penaltySEXP, SEXP iterSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type Ks(KsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XtX(XtXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xty(XtySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type xk(xkSEXP);
    Rcpp::traits::input_parameter< int >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< int& >::type iter(iterSEXP);
    ISTA_LM(p, H, K, Ks, pk, XtX, Xty, lambda, L, max_it, eps, x0, xk, penalty, iter);
    return R_NilValue;
END_RCPP
}
// FISTA_LM
void FISTA_LM(int p, int H, int K, const arma::ivec& Ks, const arma::ivec& pk, const arma::mat& XtX, const arma::vec& Xty, const arma::vec& lambda, double L, int max_it, double eps, arma::vec& x0, arma::vec& xk, int penalty, int& iter);
RcppExport SEXP _scoop_FISTA_LM(SEXP pSEXP, SEXP HSEXP, SEXP KSEXP, SEXP KsSEXP, SEXP pkSEXP, SEXP XtXSEXP, SEXP XtySEXP, SEXP lambdaSEXP, SEXP LSEXP, SEXP max_itSEXP, SEXP epsSEXP, SEXP x0SEXP, SEXP xkSEXP, SEXP penaltySEXP, SEXP iterSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type Ks(KsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XtX(XtXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xty(XtySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type xk(xkSEXP);
    Rcpp::traits::input_parameter< int >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< int& >::type iter(iterSEXP);
    FISTA_LM(p, H, K, Ks, pk, XtX, Xty, lambda, L, max_it, eps, x0, xk, penalty, iter);
    return R_NilValue;
END_RCPP
}
// ISTA_LRM
void ISTA_LRM(int p, int H, int K, const arma::ivec& Ks, const arma::ivec& pk, int n, const arma::mat& X, const arma::vec& y, const arma::vec& lambda, double L0, int max_it, double eps, arma::vec& x0, arma::vec& xk, int penalty, int& iter);
RcppExport SEXP _scoop_ISTA_LRM(SEXP pSEXP, SEXP HSEXP, SEXP KSEXP, SEXP KsSEXP, SEXP pkSEXP, SEXP nSEXP, SEXP XSEXP, SEXP ySEXP, SEXP lambdaSEXP, SEXP L0SEXP, SEXP max_itSEXP, SEXP epsSEXP, SEXP x0SEXP, SEXP xkSEXP, SEXP penaltySEXP, SEXP iterSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type Ks(KsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type L0(L0SEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type xk(xkSEXP);
    Rcpp::traits::input_parameter< int >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< int& >::type iter(iterSEXP);
    ISTA_LRM(p, H, K, Ks, pk, n, X, y, lambda, L0, max_it, eps, x0, xk, penalty, iter);
    return R_NilValue;
END_RCPP
}
// FISTA_LRM
void FISTA_LRM(int p, int H, int K, const arma::ivec& Ks, const arma::ivec& pk, int n, const arma::mat& X, const arma::vec& y, const arma::vec& lambda, double L0, int max_it, double eps, arma::vec& x0, arma::vec& xk, int penalty, int& iter);
RcppExport SEXP _scoop_FISTA_LRM(SEXP pSEXP, SEXP HSEXP, SEXP KSEXP, SEXP KsSEXP, SEXP pkSEXP, SEXP nSEXP, SEXP XSEXP, SEXP ySEXP, SEXP lambdaSEXP, SEXP L0SEXP, SEXP max_itSEXP, SEXP epsSEXP, SEXP x0SEXP, SEXP xkSEXP, SEXP penaltySEXP, SEXP iterSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type Ks(KsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type L0(L0SEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type xk(xkSEXP);
    Rcpp::traits::input_parameter< int >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< int& >::type iter(iterSEXP);
    FISTA_LRM(p, H, K, Ks, pk, n, X, y, lambda, L0, max_it, eps, x0, xk, penalty, iter);
    return R_NilValue;
END_RCPP
}
// groupnorm
arma::vec groupnorm(const arma::vec& beta, const arma::ivec& pk);
RcppExport SEXP _scoop_groupnorm(SEXP betaSEXP, SEXP pkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type pk(pkSEXP);
    rcpp_result_gen = Rcpp::wrap(groupnorm(beta, pk));
    return rcpp_result_gen;
END_RCPP
}
// coopnorm
arma::vec coopnorm(const arma::vec& beta, const arma::ivec& pk);
RcppExport SEXP _scoop_coopnorm(SEXP betaSEXP, SEXP pkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type pk(pkSEXP);
    rcpp_result_gen = Rcpp::wrap(coopnorm(beta, pk));
    return rcpp_result_gen;
END_RCPP
}
// groupnormrep
arma::vec groupnormrep(const arma::vec& beta, const arma::ivec& pk);
RcppExport SEXP _scoop_groupnormrep(SEXP betaSEXP, SEXP pkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type pk(pkSEXP);
    rcpp_result_gen = Rcpp::wrap(groupnormrep(beta, pk));
    return rcpp_result_gen;
END_RCPP
}
// elt_norm_L1
arma::vec elt_norm_L1(arma::vec x);
RcppExport SEXP _scoop_elt_norm_L1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(elt_norm_L1(x));
    return rcpp_result_gen;
END_RCPP
}
// pen_norm_L1
double pen_norm_L1(arma::vec x, arma::vec w);
RcppExport SEXP _scoop_pen_norm_L1(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(pen_norm_L1(x, w));
    return rcpp_result_gen;
END_RCPP
}
// dual_norm_L1
double dual_norm_L1(arma::vec x);
RcppExport SEXP _scoop_dual_norm_L1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(dual_norm_L1(x));
    return rcpp_result_gen;
END_RCPP
}
// proximal_L1
arma::vec proximal_L1(arma::vec x, arma::vec w, double lambda);
RcppExport SEXP _scoop_proximal_L1(SEXP xSEXP, SEXP wSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(proximal_L1(x, w, lambda));
    return rcpp_result_gen;
END_RCPP
}
// elt_norm_LINF
arma::vec elt_norm_LINF(arma::vec x);
RcppExport SEXP _scoop_elt_norm_LINF(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(elt_norm_LINF(x));
    return rcpp_result_gen;
END_RCPP
}
// pen_norm_LINF
double pen_norm_LINF(arma::vec x, arma::vec w);
RcppExport SEXP _scoop_pen_norm_LINF(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(pen_norm_LINF(x, w));
    return rcpp_result_gen;
END_RCPP
}
// dual_norm_LINF
double dual_norm_LINF(arma::vec x);
RcppExport SEXP _scoop_dual_norm_LINF(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(dual_norm_LINF(x));
    return rcpp_result_gen;
END_RCPP
}
// proximal_LINF
arma::vec proximal_LINF(arma::vec x, arma::vec w, double lambda);
RcppExport SEXP _scoop_proximal_LINF(SEXP xSEXP, SEXP wSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(proximal_LINF(x, w, lambda));
    return rcpp_result_gen;
END_RCPP
}
// elt_norm_L1L2
arma::vec elt_norm_L1L2(arma::vec x, arma::uvec pk);
RcppExport SEXP _scoop_elt_norm_L1L2(SEXP xSEXP, SEXP pkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    rcpp_result_gen = Rcpp::wrap(elt_norm_L1L2(x, pk));
    return rcpp_result_gen;
END_RCPP
}
// pen_norm_L1L2
double pen_norm_L1L2(arma::vec x, arma::uvec pk, arma::vec w);
RcppExport SEXP _scoop_pen_norm_L1L2(SEXP xSEXP, SEXP pkSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(pen_norm_L1L2(x, pk, w));
    return rcpp_result_gen;
END_RCPP
}
// dual_norm_L1L2
double dual_norm_L1L2(arma::vec x, arma::uvec pk);
RcppExport SEXP _scoop_dual_norm_L1L2(SEXP xSEXP, SEXP pkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    rcpp_result_gen = Rcpp::wrap(dual_norm_L1L2(x, pk));
    return rcpp_result_gen;
END_RCPP
}
// proximal_L1L2
arma::vec proximal_L1L2(arma::vec x, arma::uvec pk, arma::vec w, double lambda);
RcppExport SEXP _scoop_proximal_L1L2(SEXP xSEXP, SEXP pkSEXP, SEXP wSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(proximal_L1L2(x, pk, w, lambda));
    return rcpp_result_gen;
END_RCPP
}
// elt_norm_L1LINF
arma::vec elt_norm_L1LINF(arma::vec x, arma::uvec pk);
RcppExport SEXP _scoop_elt_norm_L1LINF(SEXP xSEXP, SEXP pkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    rcpp_result_gen = Rcpp::wrap(elt_norm_L1LINF(x, pk));
    return rcpp_result_gen;
END_RCPP
}
// pen_norm_L1LINF
double pen_norm_L1LINF(arma::vec x, arma::uvec pk, arma::vec w);
RcppExport SEXP _scoop_pen_norm_L1LINF(SEXP xSEXP, SEXP pkSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(pen_norm_L1LINF(x, pk, w));
    return rcpp_result_gen;
END_RCPP
}
// dual_norm_L1LINF
double dual_norm_L1LINF(arma::vec x, arma::uvec pk);
RcppExport SEXP _scoop_dual_norm_L1LINF(SEXP xSEXP, SEXP pkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    rcpp_result_gen = Rcpp::wrap(dual_norm_L1LINF(x, pk));
    return rcpp_result_gen;
END_RCPP
}
// proximal_L1LINF
arma::vec proximal_L1LINF(arma::vec x, arma::uvec pk, arma::vec w, double lambda);
RcppExport SEXP _scoop_proximal_L1LINF(SEXP xSEXP, SEXP pkSEXP, SEXP wSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(proximal_L1LINF(x, pk, w, lambda));
    return rcpp_result_gen;
END_RCPP
}
// elt_norm_COOP
arma::vec elt_norm_COOP(arma::vec x, arma::uvec pk);
RcppExport SEXP _scoop_elt_norm_COOP(SEXP xSEXP, SEXP pkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    rcpp_result_gen = Rcpp::wrap(elt_norm_COOP(x, pk));
    return rcpp_result_gen;
END_RCPP
}
// pen_norm_COOP
double pen_norm_COOP(arma::vec x, arma::uvec pk, arma::vec w);
RcppExport SEXP _scoop_pen_norm_COOP(SEXP xSEXP, SEXP pkSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(pen_norm_COOP(x, pk, w));
    return rcpp_result_gen;
END_RCPP
}
// dual_norm_COOP
double dual_norm_COOP(arma::vec x, arma::uvec pk);
RcppExport SEXP _scoop_dual_norm_COOP(SEXP xSEXP, SEXP pkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    rcpp_result_gen = Rcpp::wrap(dual_norm_COOP(x, pk));
    return rcpp_result_gen;
END_RCPP
}
// proximal_COOP
arma::vec proximal_COOP(arma::vec x, arma::uvec pk, arma::vec w, double lambda);
RcppExport SEXP _scoop_proximal_COOP(SEXP xSEXP, SEXP pkSEXP, SEXP wSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(proximal_COOP(x, pk, w, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scoop_ISTA_LM", (DL_FUNC) &_scoop_ISTA_LM, 15},
    {"_scoop_FISTA_LM", (DL_FUNC) &_scoop_FISTA_LM, 15},
    {"_scoop_ISTA_LRM", (DL_FUNC) &_scoop_ISTA_LRM, 16},
    {"_scoop_FISTA_LRM", (DL_FUNC) &_scoop_FISTA_LRM, 16},
    {"_scoop_groupnorm", (DL_FUNC) &_scoop_groupnorm, 2},
    {"_scoop_coopnorm", (DL_FUNC) &_scoop_coopnorm, 2},
    {"_scoop_groupnormrep", (DL_FUNC) &_scoop_groupnormrep, 2},
    {"_scoop_elt_norm_L1", (DL_FUNC) &_scoop_elt_norm_L1, 1},
    {"_scoop_pen_norm_L1", (DL_FUNC) &_scoop_pen_norm_L1, 2},
    {"_scoop_dual_norm_L1", (DL_FUNC) &_scoop_dual_norm_L1, 1},
    {"_scoop_proximal_L1", (DL_FUNC) &_scoop_proximal_L1, 3},
    {"_scoop_elt_norm_LINF", (DL_FUNC) &_scoop_elt_norm_LINF, 1},
    {"_scoop_pen_norm_LINF", (DL_FUNC) &_scoop_pen_norm_LINF, 2},
    {"_scoop_dual_norm_LINF", (DL_FUNC) &_scoop_dual_norm_LINF, 1},
    {"_scoop_proximal_LINF", (DL_FUNC) &_scoop_proximal_LINF, 3},
    {"_scoop_elt_norm_L1L2", (DL_FUNC) &_scoop_elt_norm_L1L2, 2},
    {"_scoop_pen_norm_L1L2", (DL_FUNC) &_scoop_pen_norm_L1L2, 3},
    {"_scoop_dual_norm_L1L2", (DL_FUNC) &_scoop_dual_norm_L1L2, 2},
    {"_scoop_proximal_L1L2", (DL_FUNC) &_scoop_proximal_L1L2, 4},
    {"_scoop_elt_norm_L1LINF", (DL_FUNC) &_scoop_elt_norm_L1LINF, 2},
    {"_scoop_pen_norm_L1LINF", (DL_FUNC) &_scoop_pen_norm_L1LINF, 3},
    {"_scoop_dual_norm_L1LINF", (DL_FUNC) &_scoop_dual_norm_L1LINF, 2},
    {"_scoop_proximal_L1LINF", (DL_FUNC) &_scoop_proximal_L1LINF, 4},
    {"_scoop_elt_norm_COOP", (DL_FUNC) &_scoop_elt_norm_COOP, 2},
    {"_scoop_pen_norm_COOP", (DL_FUNC) &_scoop_pen_norm_COOP, 3},
    {"_scoop_dual_norm_COOP", (DL_FUNC) &_scoop_dual_norm_COOP, 2},
    {"_scoop_proximal_COOP", (DL_FUNC) &_scoop_proximal_COOP, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_scoop(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
