// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// elt_norm_L1
arma::vec elt_norm_L1(arma::vec x);
RcppExport SEXP _scoop_elt_norm_L1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(elt_norm_L1(x));
    return rcpp_result_gen;
END_RCPP
}
// pen_norm_L1
double pen_norm_L1(arma::vec x, arma::vec w);
RcppExport SEXP _scoop_pen_norm_L1(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(pen_norm_L1(x, w));
    return rcpp_result_gen;
END_RCPP
}
// dual_norm_L1
double dual_norm_L1(arma::vec x);
RcppExport SEXP _scoop_dual_norm_L1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(dual_norm_L1(x));
    return rcpp_result_gen;
END_RCPP
}
// proximal_L1
arma::vec proximal_L1(arma::vec x, arma::vec w, double lambda);
RcppExport SEXP _scoop_proximal_L1(SEXP xSEXP, SEXP wSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(proximal_L1(x, w, lambda));
    return rcpp_result_gen;
END_RCPP
}
// elt_norm_LINF
arma::vec elt_norm_LINF(arma::vec x);
RcppExport SEXP _scoop_elt_norm_LINF(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(elt_norm_LINF(x));
    return rcpp_result_gen;
END_RCPP
}
// pen_norm_LINF
double pen_norm_LINF(arma::vec x, arma::vec w);
RcppExport SEXP _scoop_pen_norm_LINF(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(pen_norm_LINF(x, w));
    return rcpp_result_gen;
END_RCPP
}
// dual_norm_LINF
double dual_norm_LINF(arma::vec x);
RcppExport SEXP _scoop_dual_norm_LINF(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(dual_norm_LINF(x));
    return rcpp_result_gen;
END_RCPP
}
// proximal_LINF
arma::vec proximal_LINF(arma::vec x, arma::vec w, double lambda);
RcppExport SEXP _scoop_proximal_LINF(SEXP xSEXP, SEXP wSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(proximal_LINF(x, w, lambda));
    return rcpp_result_gen;
END_RCPP
}
// elt_norm_L1L2
arma::vec elt_norm_L1L2(arma::vec x, arma::uvec pk);
RcppExport SEXP _scoop_elt_norm_L1L2(SEXP xSEXP, SEXP pkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    rcpp_result_gen = Rcpp::wrap(elt_norm_L1L2(x, pk));
    return rcpp_result_gen;
END_RCPP
}
// pen_norm_L1L2
double pen_norm_L1L2(arma::vec x, arma::uvec pk, arma::vec w);
RcppExport SEXP _scoop_pen_norm_L1L2(SEXP xSEXP, SEXP pkSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(pen_norm_L1L2(x, pk, w));
    return rcpp_result_gen;
END_RCPP
}
// dual_norm_L1L2
double dual_norm_L1L2(arma::vec x, arma::uvec pk);
RcppExport SEXP _scoop_dual_norm_L1L2(SEXP xSEXP, SEXP pkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    rcpp_result_gen = Rcpp::wrap(dual_norm_L1L2(x, pk));
    return rcpp_result_gen;
END_RCPP
}
// proximal_L1L2
arma::vec proximal_L1L2(arma::vec x, arma::uvec pk, arma::vec w, double lambda);
RcppExport SEXP _scoop_proximal_L1L2(SEXP xSEXP, SEXP pkSEXP, SEXP wSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(proximal_L1L2(x, pk, w, lambda));
    return rcpp_result_gen;
END_RCPP
}
// elt_norm_L1LINF
arma::vec elt_norm_L1LINF(arma::vec x, arma::uvec pk);
RcppExport SEXP _scoop_elt_norm_L1LINF(SEXP xSEXP, SEXP pkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    rcpp_result_gen = Rcpp::wrap(elt_norm_L1LINF(x, pk));
    return rcpp_result_gen;
END_RCPP
}
// pen_norm_L1LINF
double pen_norm_L1LINF(arma::vec x, arma::uvec pk, arma::vec w);
RcppExport SEXP _scoop_pen_norm_L1LINF(SEXP xSEXP, SEXP pkSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(pen_norm_L1LINF(x, pk, w));
    return rcpp_result_gen;
END_RCPP
}
// dual_norm_L1LINF
double dual_norm_L1LINF(arma::vec x, arma::uvec pk);
RcppExport SEXP _scoop_dual_norm_L1LINF(SEXP xSEXP, SEXP pkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    rcpp_result_gen = Rcpp::wrap(dual_norm_L1LINF(x, pk));
    return rcpp_result_gen;
END_RCPP
}
// proximal_L1LINF
arma::vec proximal_L1LINF(arma::vec x, arma::uvec pk, arma::vec w, double lambda);
RcppExport SEXP _scoop_proximal_L1LINF(SEXP xSEXP, SEXP pkSEXP, SEXP wSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(proximal_L1LINF(x, pk, w, lambda));
    return rcpp_result_gen;
END_RCPP
}
// elt_norm_COOP
arma::vec elt_norm_COOP(arma::vec x, arma::uvec pk);
RcppExport SEXP _scoop_elt_norm_COOP(SEXP xSEXP, SEXP pkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    rcpp_result_gen = Rcpp::wrap(elt_norm_COOP(x, pk));
    return rcpp_result_gen;
END_RCPP
}
// pen_norm_COOP
double pen_norm_COOP(arma::vec x, arma::uvec pk, arma::vec w);
RcppExport SEXP _scoop_pen_norm_COOP(SEXP xSEXP, SEXP pkSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(pen_norm_COOP(x, pk, w));
    return rcpp_result_gen;
END_RCPP
}
// dual_norm_COOP
double dual_norm_COOP(arma::vec x, arma::uvec pk);
RcppExport SEXP _scoop_dual_norm_COOP(SEXP xSEXP, SEXP pkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    rcpp_result_gen = Rcpp::wrap(dual_norm_COOP(x, pk));
    return rcpp_result_gen;
END_RCPP
}
// proximal_COOP
arma::vec proximal_COOP(arma::vec x, arma::uvec pk, arma::vec w, double lambda);
RcppExport SEXP _scoop_proximal_COOP(SEXP xSEXP, SEXP pkSEXP, SEXP wSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(proximal_COOP(x, pk, w, lambda));
    return rcpp_result_gen;
END_RCPP
}

RcppExport void FISTA_LM(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport void FISTA_LRM(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport void ISTA_LM(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport void ISTA_LRM(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport void coopnorm(void *, void *, void *, void *, void *);
RcppExport void groupnorm(void *, void *, void *, void *, void *);
RcppExport void groupnormrep(void *, void *, void *, void *, void *);
RcppExport void proximal_tree_coo_standalone(void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport void proximal_tree_grp_standalone(void *, void *, void *, void *, void *, void *, void *, void *);

static const R_CallMethodDef CallEntries[] = {
    {"_scoop_elt_norm_L1", (DL_FUNC) &_scoop_elt_norm_L1, 1},
    {"_scoop_pen_norm_L1", (DL_FUNC) &_scoop_pen_norm_L1, 2},
    {"_scoop_dual_norm_L1", (DL_FUNC) &_scoop_dual_norm_L1, 1},
    {"_scoop_proximal_L1", (DL_FUNC) &_scoop_proximal_L1, 3},
    {"_scoop_elt_norm_LINF", (DL_FUNC) &_scoop_elt_norm_LINF, 1},
    {"_scoop_pen_norm_LINF", (DL_FUNC) &_scoop_pen_norm_LINF, 2},
    {"_scoop_dual_norm_LINF", (DL_FUNC) &_scoop_dual_norm_LINF, 1},
    {"_scoop_proximal_LINF", (DL_FUNC) &_scoop_proximal_LINF, 3},
    {"_scoop_elt_norm_L1L2", (DL_FUNC) &_scoop_elt_norm_L1L2, 2},
    {"_scoop_pen_norm_L1L2", (DL_FUNC) &_scoop_pen_norm_L1L2, 3},
    {"_scoop_dual_norm_L1L2", (DL_FUNC) &_scoop_dual_norm_L1L2, 2},
    {"_scoop_proximal_L1L2", (DL_FUNC) &_scoop_proximal_L1L2, 4},
    {"_scoop_elt_norm_L1LINF", (DL_FUNC) &_scoop_elt_norm_L1LINF, 2},
    {"_scoop_pen_norm_L1LINF", (DL_FUNC) &_scoop_pen_norm_L1LINF, 3},
    {"_scoop_dual_norm_L1LINF", (DL_FUNC) &_scoop_dual_norm_L1LINF, 2},
    {"_scoop_proximal_L1LINF", (DL_FUNC) &_scoop_proximal_L1LINF, 4},
    {"_scoop_elt_norm_COOP", (DL_FUNC) &_scoop_elt_norm_COOP, 2},
    {"_scoop_pen_norm_COOP", (DL_FUNC) &_scoop_pen_norm_COOP, 3},
    {"_scoop_dual_norm_COOP", (DL_FUNC) &_scoop_dual_norm_COOP, 2},
    {"_scoop_proximal_COOP", (DL_FUNC) &_scoop_proximal_COOP, 4},
    {"FISTA_LM",                     (DL_FUNC) &FISTA_LM,                     15},
    {"FISTA_LRM",                    (DL_FUNC) &FISTA_LRM,                    16},
    {"ISTA_LM",                      (DL_FUNC) &ISTA_LM,                      15},
    {"ISTA_LRM",                     (DL_FUNC) &ISTA_LRM,                     16},
    {"coopnorm",                     (DL_FUNC) &coopnorm,                      5},
    {"groupnorm",                    (DL_FUNC) &groupnorm,                     5},
    {"groupnormrep",                 (DL_FUNC) &groupnormrep,                  5},
    {"proximal_tree_coo_standalone", (DL_FUNC) &proximal_tree_coo_standalone,  8},
    {"proximal_tree_grp_standalone", (DL_FUNC) &proximal_tree_grp_standalone,  8},
    {NULL, NULL, 0}
};

RcppExport void R_init_scoop(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
