# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ISTA_LM <- function(p, H, K, Ks, pk, XtX, Xty, lambda, L, max_it, eps, x0, xk, penalty, iter) {
    invisible(.Call(`_scoop_ISTA_LM`, p, H, K, Ks, pk, XtX, Xty, lambda, L, max_it, eps, x0, xk, penalty, iter))
}

FISTA_LM <- function(p, H, K, Ks, pk, XtX, Xty, lambda, L, max_it, eps, x0, xk, penalty, iter) {
    invisible(.Call(`_scoop_FISTA_LM`, p, H, K, Ks, pk, XtX, Xty, lambda, L, max_it, eps, x0, xk, penalty, iter))
}

ISTA_LRM <- function(p, H, K, Ks, pk, n, X, y, lambda, L0, max_it, eps, x0, xk, penalty, iter) {
    invisible(.Call(`_scoop_ISTA_LRM`, p, H, K, Ks, pk, n, X, y, lambda, L0, max_it, eps, x0, xk, penalty, iter))
}

FISTA_LRM <- function(p, H, K, Ks, pk, n, X, y, lambda, L0, max_it, eps, x0, xk, penalty, iter) {
    invisible(.Call(`_scoop_FISTA_LRM`, p, H, K, Ks, pk, n, X, y, lambda, L0, max_it, eps, x0, xk, penalty, iter))
}

groupnorm <- function(beta, pk) {
    .Call(`_scoop_groupnorm`, beta, pk)
}

coopnorm <- function(beta, pk) {
    .Call(`_scoop_coopnorm`, beta, pk)
}

groupnormrep <- function(beta, pk) {
    .Call(`_scoop_groupnormrep`, beta, pk)
}

elt_norm_L1 <- function(x) {
    .Call(`_scoop_elt_norm_L1`, x)
}

pen_norm_L1 <- function(x, w) {
    .Call(`_scoop_pen_norm_L1`, x, w)
}

dual_norm_L1 <- function(x) {
    .Call(`_scoop_dual_norm_L1`, x)
}

proximal_L1 <- function(x, w, lambda) {
    .Call(`_scoop_proximal_L1`, x, w, lambda)
}

elt_norm_LINF <- function(x) {
    .Call(`_scoop_elt_norm_LINF`, x)
}

pen_norm_LINF <- function(x, w) {
    .Call(`_scoop_pen_norm_LINF`, x, w)
}

dual_norm_LINF <- function(x) {
    .Call(`_scoop_dual_norm_LINF`, x)
}

proximal_LINF <- function(x, w, lambda) {
    .Call(`_scoop_proximal_LINF`, x, w, lambda)
}

elt_norm_L1L2 <- function(x, pk) {
    .Call(`_scoop_elt_norm_L1L2`, x, pk)
}

pen_norm_L1L2 <- function(x, pk, w) {
    .Call(`_scoop_pen_norm_L1L2`, x, pk, w)
}

dual_norm_L1L2 <- function(x, pk) {
    .Call(`_scoop_dual_norm_L1L2`, x, pk)
}

proximal_L1L2 <- function(x, pk, w, lambda) {
    .Call(`_scoop_proximal_L1L2`, x, pk, w, lambda)
}

elt_norm_L1LINF <- function(x, pk) {
    .Call(`_scoop_elt_norm_L1LINF`, x, pk)
}

pen_norm_L1LINF <- function(x, pk, w) {
    .Call(`_scoop_pen_norm_L1LINF`, x, pk, w)
}

dual_norm_L1LINF <- function(x, pk) {
    .Call(`_scoop_dual_norm_L1LINF`, x, pk)
}

proximal_L1LINF <- function(x, pk, w, lambda) {
    .Call(`_scoop_proximal_L1LINF`, x, pk, w, lambda)
}

elt_norm_COOP <- function(x, pk) {
    .Call(`_scoop_elt_norm_COOP`, x, pk)
}

pen_norm_COOP <- function(x, pk, w) {
    .Call(`_scoop_pen_norm_COOP`, x, pk, w)
}

dual_norm_COOP <- function(x, pk) {
    .Call(`_scoop_dual_norm_COOP`, x, pk)
}

proximal_COOP <- function(x, pk, w, lambda) {
    .Call(`_scoop_proximal_COOP`, x, pk, w, lambda)
}

